"use client";
import { useEffect, useState } from "react";
import Shell from "@/components/Shell";
import Icon from "@/components/Icon";
type Suggestion = { id: string; creator_id: string; shopee_url: string; reason: string | null; status: "pending" | "approved" | "rejected"; created_at: string; creator: { name: string | null; email: string } | null };
const labels = { pending: "Pendente", approved: "Aprovada", rejected: "Recusada" };
export default function AdminSuggestionsPage() {
  const [items, setItems] = useState<Suggestion[]>([]), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  useEffect(() => { fetch("/api/admin/product-suggestions").then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setItems(body.suggestions ?? []); }).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  async function decide(id: string, status: "approved" | "rejected") { const response = await fetch("/api/admin/product-suggestions", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status }) }); const body = await response.json(); if (!response.ok) { setError(body.error ?? "Não foi possível atualizar."); return; } setItems((current) => current.map((item) => item.id === id ? { ...item, status: body.suggestion.status } : item)); }
  return <Shell admin><div className="page-head"><div><p className="eyebrow">Conteúdo da comunidade</p><h1>Sugestões de produtos</h1><p>Veja o que as criadoras querem gravar e mantenha o catálogo sempre interessante.</p></div></div>{error && <div className="card form-error" role="alert">{error}</div>}{loading ? <div className="card empty-suggestions">Carregando sugestões...</div> : <div className="card table-wrap"><table className="data-table suggestion-table"><thead><tr><th>Criadora</th><th>Produto Shopee</th><th>Motivo</th><th>Status</th><th>Ações</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.creator?.name ?? "Criadora"}</strong><small className="muted">{item.creator?.email ?? item.creator_id}</small></td><td><a href={item.shopee_url} target="_blank" rel="noreferrer" className="suggestion-link">Abrir produto ↗</a></td><td>{item.reason || <span className="muted">Sem motivo</span>}</td><td><span className={`suggestion-status suggestion-status-${item.status}`}>{labels[item.status]}</span></td><td>{item.status === "pending" ? <div className="suggestion-actions"><button className="button button-primary" onClick={() => decide(item.id, "approved")}><Icon name="check" size={14} /> Aprovar</button><button className="button button-light" onClick={() => decide(item.id, "rejected")}>Rejeitar</button></div> : <span className="muted">Analisada</span>}</td></tr>)}</tbody></table>{!items.length && <p className="empty-suggestions">Nenhuma sugestão recebida.</p>}</div>}</Shell>;
}
