"use client";
import { useState } from "react";
import type { ModerationVideo } from "@/lib/dashboard-data";
import { getDriveEmbedUrl } from "@/lib/drive-embed";
import { useToast } from "@/components/ToastProvider";

export default function ApprovalQueue({ initialVideos }: { initialVideos: ModerationVideo[] }) {
  const { showToast } = useToast();
  const [videos, setVideos] = useState(initialVideos); const [error, setError] = useState(""); const [busy, setBusy] = useState<string | null>(null); const [rejecting, setRejecting] = useState<string | null>(null); const [reason, setReason] = useState("");
  async function moderate(id: string, action: "aprovar" | "reprovar", motivo?: string) {
    setBusy(id); setError("");
    try { const response = await fetch(`/api/videos/${id}/${action}`, { method: "POST", headers: action === "reprovar" ? { "Content-Type": "application/json" } : undefined, body: action === "reprovar" ? JSON.stringify({ motivo }) : undefined }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Não foi possível atualizar o vídeo."); setVideos((current) => current.filter((video) => video.id !== id)); setRejecting(null); setReason(""); showToast({ title: action === "aprovar" ? "Vídeo aprovado" : "Vídeo reprovado", description: action === "aprovar" ? "O vídeo foi aprovado e já pode seguir no catálogo." : "A recusa e o motivo foram enviados para a criadora.", type: "success" }); }
    catch (cause) { const description = cause instanceof Error ? cause.message : "Não foi possível atualizar o vídeo."; setError(description); showToast({ title: "Erro na moderação", description, type: "error" }); } finally { setBusy(null); }
  }
  function openReject(id: string) { setRejecting(id); setReason(""); setError(""); }
  function cancelReject() { setRejecting(null); setReason(""); }
  if (!videos.length) return <div className="card"><p>Nenhum vídeo pendente de aprovação.</p></div>;
  return <div className="approval-list">{error && <p className="form-error">{error}</p>}{videos.map((video) => <div className="approval-list-item" key={video.id}><img src={video.productImage || "https://placehold.co/48x48?text=UGC"} alt="" width={48} height={48} /><div className="approval-list-main"><iframe className="approval-video" src={getDriveEmbedUrl(video.videoUrl)} title={`Vídeo de ${video.creatorName}`} allow="autoplay" allowFullScreen style={{ border: 0 }} /><strong>{video.creatorName}</strong><span>{video.productName}</span><a className="affiliate-small" href={video.affiliateLink} target="_blank" rel="noopener noreferrer">Link de afiliado</a></div><div className="approval-actions"><button className="button button-primary" disabled={busy === video.id} onClick={() => moderate(video.id, "aprovar")}>Aprovar</button><button className="button button-ghost" disabled={busy === video.id} onClick={() => openReject(video.id)}>Reprovar</button></div></div>)}{rejecting && <div className="reject-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) cancelReject(); }}><div className="reject-modal" role="dialog" aria-modal="true" aria-labelledby="reject-title"><h2 id="reject-title">Motivo da recusa</h2><p>Explique o que a criadora precisa ajustar antes de reenviar o vídeo.</p><textarea id="reject-reason" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Ex.: inclua uma CTA para clicar em Saiba mais..." rows={5} autoFocus /><div><button className="button button-primary" disabled={busy === rejecting || !reason.trim()} onClick={() => moderate(rejecting, "reprovar", reason.trim())}>{busy === rejecting ? "Salvando..." : "Confirmar recusa"}</button><button className="button button-ghost" disabled={busy === rejecting} onClick={cancelReject}>Cancelar</button></div></div></div>}</div>;
}
