"use client";
import { FormEvent, useEffect, useState } from "react";
import Shell from "@/components/Shell";
import Icon from "@/components/Icon";
type Suggestion = { id: string; shopee_url: string; reason: string | null; status: "pending" | "approved" | "rejected"; created_at: string };
const statusLabel = { pending: "Em análise", approved: "Aprovada", rejected: "Recusada" };
export default function SuggestProductPage() {
  const [url, setUrl] = useState(""), [reason, setReason] = useState(""), [suggestions, setSuggestions] = useState<Suggestion[]>([]), [message, setMessage] = useState(""), [error, setError] = useState(""), [loading, setLoading] = useState(false);
  useEffect(() => { fetch("/api/product-suggestions").then(async (response) => { if (response.ok) setSuggestions((await response.json()).suggestions ?? []); }); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); setLoading(true); const response = await fetch("/api/product-suggestions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ shopee_url: url, reason }) }); const body = await response.json(); setLoading(false); if (!response.ok) { setError(body.error ?? "Não foi possível enviar sua sugestão."); return; } setSuggestions((current) => [body.suggestion, ...current]); setUrl(""); setReason(""); setMessage("Sugestão enviada! Vamos analisar com carinho."); }
  return <Shell><div className="page-head"><div><p className="eyebrow">Ajude a construir o catálogo</p><h1>Sugerir produto</h1><p>Conhece um produto da Shopee que daria um vídeo incrível? Manda pra gente.</p></div></div><div className="suggest-product-layout"><form className="card suggest-product-form" onSubmit={submit}><div className="suggest-form-icon"><Icon name="cart" size={21} /></div><h2>Qual produto você quer ver por aqui?</h2><p>Envie o link direto da Shopee. O motivo é opcional, mas ajuda a gente a entender sua ideia.</p><label>Link do produto Shopee *<input required type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://shopee.com.br/..." /></label><label>Por que você sugere esse produto?<textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Ex.: acho que combina com meu público..." rows={4} /></label>{error && <p className="form-error" role="alert">{error}</p>}{message && <p className="form-success" role="status"><Icon name="check" size={16} />{message}</p>}<button className="button button-primary" disabled={loading} type="submit">{loading ? "Enviando..." : "Enviar sugestão →"}</button></form><aside className="suggest-product-tip"><span className="academy-icon"><Icon name="warning" size={18} /></span><h2>Uma boa sugestão ajuda todo mundo</h2><p>Se o produto for aprovado, ele entra no catálogo para você e outras criadoras gravarem vídeos.</p></aside></div><div className="suggestion-history"><div className="section-title"><div className="section-icon"><Icon name="calendar" size={18} /></div><h2>Minhas sugestões <span className="muted">({suggestions.length})</span></h2></div>{suggestions.length === 0 ? <div className="card empty-suggestions">Você ainda não enviou nenhuma sugestão.</div> : <div className="card suggestion-history-list">{suggestions.map((item) => <div className="suggestion-history-row" key={item.id}><div><strong>{item.shopee_url}</strong>{item.reason && <span>{item.reason}</span>}<small>{new Date(item.created_at).toLocaleDateString("pt-BR")}</small></div><span className={`suggestion-status suggestion-status-${item.status}`}>{statusLabel[item.status]}</span></div>)}</div>}</div></Shell>;
}
